common: &default_settings
  license_key: '*******************************'
  app_name: Twitalytics

staging:
  <<: *default_settings
  monitor_mode: true

production:
  <<: *default_settings
  monitor_mode: false
