source 'https://rubygems.org'

# START:ruby
ruby '2.2.3', :engine => 'jruby', :engine_version => '9.0.5.0'
# END:ruby

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'

gem 'rails_12factor'

# The database for Active Record
# START:db
gem 'activerecord-jdbcsqlite3-adapter', group: :development
gem 'activerecord-jdbcpostgresql-adapter', group: :production
# END:db

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# See https://github.com/rails/execjs#readme for more supported runtimes
# START:therubyrhino
gem 'therubyrhino'
# END:therubyrhino

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# START:torquebox
gem 'torquebox', '4.0.0.beta2'
# END:torquebox

# START:tzinfo
gem 'tzinfo-data', platforms: [:mingw, :mswin, :jruby]
# END:tzinfo
