# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e96489fd2d0bdbdfb22858056a765291ab4a13dd561dd45514f1b2f702e466a8ce6378d8acc6474ea731e5082450027d2976f692d525a35449af8c0ae242c22

test:
  secret_key_base: d56291612a6c3c7fdfb17431a656f998fac11bd45eafdd1562835956ff779f61f6290d2401eceb8680a94f6d50e431806186061de9f2da17d0df81f260347062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
